### ISSUE TITLE
工具询问

### ISSUE THREAD

**Issue by ShaneHX** [ayesawyer/ayesawyer.github.io#1]
你好，我看你的逆向系列博客写得很好，有一个问题，你在<逆向练习7>里面使用的绘图工具是什么？

**Comment by ayesawyer** [comment]
你好，谢谢你的关注，你问的是这个图吗？



这是ida的汇编窗口在图形视图模式下的显示，在程序分支很多的情况下，通过“ctrl+鼠标滑轮”缩小ida的图形显示大小就会形成这样的效果，然后我是直接截图，在电脑自带的画图工具中进行编辑添加注释的。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ShaneHan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 中午11:30
收件人:&nbsp;"ayesawyer/ayesawyer.github.io"<ayesawyer.github.io@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ayesawyer/ayesawyer.github.io] 工具询问 (#1)





 
你好，我看你的逆向系列博客写得很好，有一个问题，你在<逆向练习7&gt;里面使用的绘图工具是什么？

**Comment by ShaneHX** [comment]
好的，感谢
